# Generated by Django 6.0.4 on 2026-04-12 16:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Post_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, null=True)),
                ('Vacancy', models.PositiveIntegerField(null=True)),
                ('Category', models.CharField(choices=[('Developer', 'Developer'), ('Banking', 'Banking'), ('HR', 'HR'), ('Education', 'Education')], max_length=20, null=True)),
                ('Job_Description', models.TextField(null=True)),
                ('Skills_Set', models.TextField(null=True)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Deadline', models.DateField(null=True)),
                ('Create_At', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Seeker_Profile_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Picture', models.ImageField(null=True, upload_to='media/')),
                ('Address', models.TextField(null=True)),
                ('Phone', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter_Profile_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=225, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Address', models.TextField(null=True)),
                ('Phone', models.CharField(max_length=20, null=True)),
                ('Logo', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Apply_Job_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resume', models.FileField(null=True, upload_to='media/')),
                ('Applied_At', models.DateField(auto_now_add=True, null=True)),
                ('Applied_Job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seeker_Applied_Job', to='Job_Portal_App.job_post_model')),
                ('Applied_By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Job_Portal_App.job_seeker_profile_model')),
            ],
        ),
        migrations.AddField(
            model_name='job_post_model',
            name='Posted_By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Job_Portal_App.recruiter_profile_model'),
        ),
        migrations.CreateModel(
            name='User_Info_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Display_Name', models.CharField(max_length=255, null=True)),
                ('User_Types', models.CharField(choices=[('Seeker', 'Seeker'), ('Recruiter', 'Recruiter')], max_length=25, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='recruiter_profile_model',
            name='Recruiter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recruiter_Profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job_seeker_profile_model',
            name='Seeker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seeker_Profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
