# Generated by Django 6.0.4 on 2026-04-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerprofilemodel',
            old_name='user',
            new_name='seeker',
        ),
        migrations.RenameField(
            model_name='recruiterprofilemodel',
            old_name='user',
            new_name='recruiter',
        ),
        migrations.AlterField(
            model_name='jobseekerprofilemodel',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofilemodel',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofilemodel',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='seeker_photos/'),
        ),
        migrations.AlterField(
            model_name='recruiterprofilemodel',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofilemodel',
            name='company_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofilemodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofilemodel',
            name='logo',
            field=models.ImageField(null=True, upload_to='recruiter_logos/'),
        ),
        migrations.AlterField(
            model_name='recruiterprofilemodel',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='user_types',
            field=models.CharField(choices=[('Seeker', 'Seeker'), ('Recruiter', 'Recruiter')], max_length=25, null=True),
        ),
    ]
